language: python

python:
  - "3.5"

env:
  - DJANGO_SETTINGS_MODULE=durangoproductive.settings.test

install:
  - pip install -r requirements/base.txt
  - pip install -r requirements/test.txt
  - npm install --production
  - bower install

# command to run tests, e.g. python setup.py test
script:
  cd durangoproductive;python manage.py test --settings=durangoproductive.settings.test
