language: python

python:
  - "3.5"

env:
  - DJANGO_SETTINGS_MODULE=durangoproductive.settings.test

install:
  - pip install -r requirements.txt
  - npm install --production
  - bower install

# command to run tests, e.g. python setup.py test
script:
  python durangoproductive/manage.py test
